### ISSUE TITLE
Steam groups are not applied

### ISSUE THREAD

**Issue by kaenganxt** [AnuraNet/AnuraBot#1]
I tried to add Portal 2 as a game, but nothing happened :(

**Comment by LukBukkit** [comment]
This happend because Steam now uses https and not http, so my string replacement in [RequestHandler:70](https://github.com/AnuraNet/AnuraBot/blob/master/web/src/main/kotlin/de/anura/bot/web/RequestHandler.kt#L70) broke.

**Comment by LukBukkit** [comment]
I added in the [last commit](https://github.com/AnuraNet/AnuraBot/commit/7388ad48ae5bc5c8c47cb7e19c91349e6b45a5e3) debug messages. Maybe these help to identify the problem. 
It also could be caused by the join check delay. I lowered it to one minute.

**Comment by LukBukkit** [comment]
I'll close this issue now because of the lack of activity. But if the debug message tell an interesting story feel free to reopen this issue.
