### ISSUE TITLE
Api key

### ISSUE THREAD

**Issue by szogun1910** [AnuraNet/AnuraBot#14]
Hey, I have an api problem, after generating it and entering it into config when starting the application

```
teamspeak@xxxx:~/anura$ java -jar web-1.0-SNAPSHOT-jar-with-dependencies.jar
[INFO] de.anura.bot.BotStartupKt - Your Steam API Key is valid

```

`[steam]
; The Steam web api key is used for getting the games of a user
; You can get one here: http://steamcommunity.com/dev/apikey
api_key = 26CC97D49BFF6C26DF37E5E80xxxxxx`

**Comment by LukBukkit** [comment]
The message
```txt
[INFO] de.anura.bot.BotStartupKt - Your Steam API Key is valid
```
indicates that your Steam API key is correct (= valid) and can be used. So, everything should be fine.
