### ISSUE TITLE
Not all users get the groups when adding new timegroups

### ISSUE THREAD

**Issue by kaenganxt** [AnuraNet/AnuraBot#3]
I added a time group with 0 seconds as the minimum time to have a default group.

One member of the total ten connected clients didn't have the group after that.

He had the exactly same groups as another user in the same channel.

**Comment by LukBukkit** [comment]
It could be caused by the fact that he talked very often and because of the fixed issues no time was recorded for him and the group check wanted he time difference to be greater than 0. It could also be caused by an error in te `listen` function in the TimeGroups class. I'll look into this too

**Comment by LukBukkit** [comment]
The group check was once again improved in the commit [91e5c7f](https://github.com/AnuraNet/AnuraBot/commit/91e5c7fc122d7b71ccc541b0383797aff281f8ca), so this should work way better than before. If such issues still occurss just reopen this issue.
