### ISSUE TITLE
Select shown games

### ISSUE THREAD

**Issue by LukBukkit** [AnuraNet/AnuraBot#8]
**Is your feature request related to a problem? Please describe.**
When users own very many games and there're a lot of Teamspeak groups for Steam games, you can quickly lose the overview of the games.

**Describe the solution you'd like**
Users should be able to select the games they want to show on the Teamspeak. The number of games they can select should be limited.

**Implementation**
- [x] Add a entry to the configuration to change the maximum amount of shown games
- [x] Add two routes (show the page, saving the selection) on the web server
- [x] Create a simple web page with checkboxes and the names of the games
- [x] Check via Javascript that the user doesn't select too many games
- [x] Check this also on the server side
- [x] Create a table for this relation
- [x] Add a link to the page to the message when a joins the `Connect` channel
- [x] Add the correct groups on join

Maybe we can also cache / save the games of the user, to check for changes in their libraries.
When changes occur, we can inform them, that he/she can add this game to his/her Teamspeak groups via the webpage. 
But I think, we'll need another issue for this.

**Comment by hibo98** [comment]
Saving of the settings don't work.
If I choose my games to display nothing happens and also the database has no settings saved.
